
import java.awt.Color;
import java.awt.FlowLayout;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author viren
 */
public class srt extends javax.swing.JFrame {

    /**
     * Creates new form srt
     */
    public srt(int a) {
        initComponents();
           int size = a;
       loadtable(size);
    }
   public void loadtable(int size)
{
     DefaultTableModel model=(DefaultTableModel)table.getModel();//to perform operation o table like add row, delete row, data retrive
           table.setModel(model);
           model.setRowCount(0);//to set row blank intially
           Object row[]=new Object[size];
           while(size!=0)
           {
                model.addRow(row);
                size--;
           }
             for(int i=0; i<model.getRowCount(); i++)
                for(int j=0; j<model.getColumnCount(); j++)
                        {  model.setValueAt(0, i,j);
                     
                        }
}
    private srt() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnget = new javax.swing.JButton();
        avgwt = new javax.swing.JTextField();
        avgtat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SHORTEST REMAINING TIME");
        jLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel1PropertyChange(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Process", "Arrival Time", "Burst Time", "ct", "tat", "Witing Time"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btnget.setFont(new java.awt.Font("Cambria", 1, 11)); // NOI18N
        btnget.setText("Get Waiting Time");
        btnget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetActionPerformed(evt);
            }
        });

        avgwt.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        avgtat.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel4.setText("Avg. TurnAround Time");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel3.setText("Avg. Waiting Time");

        btnexit.setFont(new java.awt.Font("Cambria", 1, 11)); // NOI18N
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Cambria", 1, 11)); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnget, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avgwt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avgtat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgwt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnget))
                .addGap(18, 18, 18)
                .addComponent(btnexit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(avgtat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnback))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void btngetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) table.getModel();
        int at[]=new int [model.getRowCount()];
        int bt[]=new int [model.getRowCount()];
        int ct[]=new int [model.getRowCount()];
        int wt[]=new int [model.getRowCount()];
        int tat[]=new int [model.getRowCount()];
        int p[]=new int [model.getRowCount()];
        int k[]=new int [model.getRowCount()];
           int f[]=new int [model.getRowCount()];
        int n=model.getRowCount();
        for(int i=0; i<model.getRowCount(); i++)
        {
            p[i]=Integer.parseInt(model.getValueAt(i,0).toString());
            at[i]=Integer.parseInt(model.getValueAt(i,1).toString());
            bt[i]=Integer.parseInt(model.getValueAt(i,2).toString());
            f[i]=0;
            k[i]=bt[i];
        }
        
        int tot=0,st=0,v=0;
        
         while(true){
	    	int min=99,c=n;
	    	if (tot==n)
	    		break;
	    	
	    	for ( int i=0;i<n;i++)
	    	{
	    		if ((at[i]<=st) && (f[i]==0) && (bt[i]<=min))
	    		{	
	    			min=bt[i];
	    			c=i;
	    		}
	    	}
	    	
	    	if (c==n)
                {st++;
                 // gantt(v,-1);
                  //v++;
                }
	    	else
	    	{
	    		bt[c]--;// minus 1 burst time of running process
	    		st++;// adding 1 on the system time which is utilissed by the burst time 
	    		if (bt[c]==0)//burst time of any process become zero then we some the completion time with the system time st
	    		{
	    			ct[c]= st;
	    			f[c]=1;
	    			tot++;
	    		}
                       // gantt(v,p[c]);
                       // v++;
	    	}
	    }
	   double total_wt=0,  total_tat=0;
	    for(int i=0;i<n;i++)
	    {
	    	tat[i] = ct[i] - at[i];
	    	wt[i] = tat[i] - k[i];
	         total_wt+=wt[i];
                 total_tat+=tat[i];
	    }
	 avgwt.setText((double)Math.round(total_wt)/n+"");  
          avgtat.setText((double)Math.round(total_tat)/n+""); 

        for(int i=0; i<model.getRowCount(); i++)
    {  model.setValueAt(at[i], i,1);
      model.setValueAt(p[i], i,0);
      model.setValueAt(k[i], i,2);
        model.setValueAt(ct[i], i,3);
          model.setValueAt(tat[i], i,4);
              model.setValueAt(wt[i], i,5);
    }
    }//GEN-LAST:event_btngetActionPerformed

    private void jLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1PropertyChange

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
             System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
         welcome w = new welcome();
        w.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnbackActionPerformed
  /*public void gantt(int v,int p)
    {
        FlowLayout fl=new FlowLayout(FlowLayout.LEFT);
       setLayout(fl);

        JLabel lbl[]=new JLabel[100];
        JPanel j=new JPanel();
       j.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        j.setBounds(-20,0, WIDTH, HEIGHT);
          add(j);
         
       
        j.setForeground(Color.BLACK);
        
     
            lbl[v]=new JLabel("   "+p+"   ");
            j.add(lbl[v]);
            lbl[v].setBorder(BorderFactory.createLineBorder(Color.black));
        switch (p) {
            case 1:
                j.setBackground(Color.red);
                break;
            case 2:
                j.setBackground(Color.blue);
                break;
            case 3:
                j.setBackground(Color.yellow);
                break;
            case 4:
                j.setBackground(Color.orange);
                break;
            case 5:
                j.setBackground(Color.green);
                break;
            case 6:
                j.setBackground(Color.pink);
                break;
            case 7:
                j.setBackground(Color.cyan);
                break;
            case 8:
                j.setBackground(Color.gray);
                break;
            case 9:
                j.setBackground(Color.orange);
                break;
            case -1:
                j.setBackground(Color.black);
                break;
            default:
                j.setBackground(Color.magenta);
                break;
        }
            j.setVisible(true);
        
    } */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(srt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(srt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(srt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(srt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new srt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avgtat;
    private javax.swing.JTextField avgwt;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
